const CHANGE_TOTAL_PAGES = 'CHANGE_TOTAL_PAGES'
const CHANGE_ACTUAL_PAGE = 'CHANGE_ACTUAL_PAGE'
const PREVIOUS_PAGE = 'PREVIOUS_PAGE'
const NEXT_PAGE = 'NEXT_PAGE'

export { 
    CHANGE_TOTAL_PAGES,
    CHANGE_ACTUAL_PAGE,
    PREVIOUS_PAGE,
    NEXT_PAGE
}
